"""API details"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['ep_desc', 'list_pyskills', 'allow', 'chk_dest', 'AllowPolicy', 'PosAllowPolicy', 'PathWritePolicy', 'OpenWritePolicy',
           'doc', 'pyskills_dir', 'ensure_pyskills_dir', 'clear_mod', 'enable_pyskill', 'register_pyskill',
           'disable_pyskill', 'delete_pyskill', '__pytools__']

# %% ../nbs/00_core.ipynb #38e384dc
from fastcore.utils import *
from fastcore.docments import MarkdownRenderer
from fastcore.xdg import *
from importlib.metadata import entry_points
from inspect import signature
import importlib.util, types, inspect, collections, ast, site

# %% ../nbs/00_core.ipynb #6dda45ba
def ep_desc(ep):
    "First paragraph of docstring for entry point `ep`, without importing it"
    spec = importlib.util.find_spec(ep.value.split(':')[0])
    if not spec or not spec.origin: return None
    tree = ast.parse(Path(spec.origin).read_text())
    doc = ast.get_docstring(tree)
    if not doc: return None
    return doc.split('\n\n')[0]

# %% ../nbs/00_core.ipynb #d3233c49
@llmtool
def list_pyskills():
    """Returns {module: description} for all pyskills. To load a module, use `import {module}` then view `doc({module}).
    **NB**: pyskills are *THE* critical way to extend functionality. *ALWAYS* check for pyskills to help with tasks.
    If unsure whether a particular pyskill might help, load it and grabs its docs to see!"""
    return {ep.value: ep_desc(ep) for ep in entry_points().select(group='pyskills')}

# %% ../nbs/00_core.ipynb #e5adaf7a
__pytools__ = collections.defaultdict(set)

# %% ../nbs/00_core.ipynb #3c64526e
_all_ = ['__pytools__']

# %% ../nbs/00_core.ipynb #a7f5fc60
def allow(*c, allow_policy=None): # Callable that raises if call not allowed
    "Add all items in `c` to `__pytools__`, optionally constrained by `allow_policy`"
    def _wrap(v):
        if allow_policy is None or v is ... or isinstance(v, tuple): return v
        return (v, allow_policy)
    for o in c:
        if isinstance(o, dict):
            for k,v in o.items(): __pytools__[k].update(_wrap(x) for x in listify(v))
        else:
            objclass = getattr(o, '__objclass__', None)
            if objclass is not None:
                __pytools__[objclass].add(_wrap(o.__name__))
                continue
            qualname = getattr(o, '__qualname__', '') or ''
            mod = sys.modules.get(getattr(o, '__module__', '__main__'), sys.modules.get('__main__'))
            if '.' in qualname:
                cls = getattr(mod, qualname.rsplit('.', 1)[0], None)
                if cls is not None:
                    __pytools__[cls].add(_wrap(o.__name__))
                    continue
            __pytools__[mod].add(_wrap(o.__name__))
    if len(c)==1 and callable(c[0]): return c[0]

# %% ../nbs/00_core.ipynb #a3124a91
def chk_dest(p, ok_dests):
    resolved = str(Path(p).resolve())
    if not any(resolved == (rd := str(Path(d).expanduser().resolve())) or resolved.startswith(rd + '/') for d in ok_dests):
        raise PermissionError(f"Dest '{p}' not allowed; permitted: {ok_dests}")

# %% ../nbs/00_core.ipynb #59efbf64
class AllowPolicy:
    "Base for allow destination policies"
    def __call__(self, obj, args, kwargs, ok_dests): raise NotImplementedError

class PosAllowPolicy(AllowPolicy):
    "Check positional/keyword arg is an allowed destination"
    def __init__(self, pos=0, kw=None): store_attr()
    def __call__(self, obj, args, kwargs, ok_dests):
        p = kwargs.get(self.kw) if self.kw and self.kw in kwargs else args[self.pos] if self.pos < len(args) else None
        if p is not None: chk_dest(p, ok_dests)

class PathWritePolicy(AllowPolicy):
    "Check resolved Path self, optionally also target args"
    def __init__(self, target_pos=None, target_kw=None): store_attr()
    def __call__(self, obj, args, kwargs, ok_dests):
        chk_dest(obj, ok_dests)
        if self.target_pos is not None and self.target_pos < len(args): chk_dest(args[self.target_pos], ok_dests)
        if self.target_kw and self.target_kw in kwargs: chk_dest(kwargs[self.target_kw], ok_dests)

class OpenWritePolicy(AllowPolicy):
    "Check open() only when mode is writable"
    def __call__(self, obj, args, kwargs, ok_dests):
        mode = kwargs.get('mode', args[1] if len(args) > 1 else 'r')
        if any(c in mode for c in 'wax+'): chk_dest(args[0] if args else kwargs.get('file'), ok_dests)

# %% ../nbs/00_core.ipynb #7492f01d
def doc(sym)->str:
    "Docs for `sym`. modules: classes/functions with 1st docstring line; classes: method sigs; functions: sig+docments"
    if isinstance(sym, type): return _doc_class(sym)
    if isinstance(sym, types.ModuleType): return _doc_module(sym)
    return str(MarkdownRenderer(sym))

def _fmt_method(name, method, prefix=''):
    try: sig = str(signature(method))
    except (ValueError, TypeError): sig = '(...)'
    d = getattr(method, '__doc__', None)
    res = f'    {prefix}def {name}{sig}: ...'
    if d and name != '__init__': res += f'  # {d.splitlines()[0].strip()}'
    return res

# %% ../nbs/00_core.ipynb #da79ca9b
def _doc_class(sym):
    bases = ','.join(b.__name__ for b in sym.__mro__[1:-1]) if sym.__mro__[1:-1] else ''
    parts = [f'class {sym.__name__}({bases}):' if bases else f'class {sym.__name__}:']
    init = getattr(sym, '__init__', None)
    if init and init is not object.__init__: parts.append(_fmt_method('__init__', init))
    for name,raw in sorted(sym.__dict__.items()):
        if name.startswith('_'): continue
        if isinstance(raw, property): parts.append(_fmt_method(name, raw.fget, '@property\n    '))
        elif isinstance(raw, classmethod): parts.append(_fmt_method(name, raw.__func__, '@classmethod\n    '))
        elif isinstance(raw, staticmethod): parts.append(_fmt_method(name, raw.__func__, '@staticmethod\n    '))
        elif callable(raw): parts.append(_fmt_method(name, raw))
    d = sym.__doc__ or (init and init.__doc__)
    if d: parts.insert(1, '    """' + inspect.cleandoc(d).replace('\n', '\n    ') + '"""')
    return parts[0] + '\n' + '\n'.join(parts[1:])

# %% ../nbs/00_core.ipynb #8009e36f
def _fmt_allows(mod):
    src = inspect.getsource(mod)
    tree = ast.parse(src)
    lines = src.splitlines()
    calls = [node for node in ast.walk(tree) if isinstance(node, ast.Expr)
             and isinstance(node.value, ast.Call) and ast.unparse(node.value.func) == 'allow']
    if not calls: return ''
    return '\nallows:\n' + '\n'.join(f'- {ast.unparse(node.value)}' for node in calls)

# %% ../nbs/00_core.ipynb #e8d8c5fa
def _doc_module(mod):
    parts = [f'module {mod.__name__}:']
    if mod.__doc__: parts.append('"""' + inspect.cleandoc(mod.__doc__) + '"""\n')
    names = getattr(mod, '__all__', None)
    if names is None:
        names = [n for n in sorted(dir(mod)) 
            if not n.startswith('_') and getattr(getattr(mod, n, None), '__module__', None)==mod.__name__]
    for name in names:
        obj = getattr(mod, name, None)
        if obj is None: continue
        ds = getattr(obj, '__doc__', None)
        if not ds and isinstance(obj, type): ds = getattr(getattr(obj, '__init__', None), '__doc__', None)
        d = (ds or '').splitlines()
        comment = f': ...  # {d[0].strip()}' if d and d[0].strip() else ''
        if isinstance(obj, type):
            bases = ','.join(b.__name__ for b in obj.__mro__[1:-1])
            base_str = f'({bases})' if bases else ''
            parts.append(f'class {name}{base_str}{comment}')
        elif callable(obj):
            try: sig = str(signature(obj))
            except (ValueError, TypeError): sig = '(...)'
            parts.append(f'def {name}{sig}{comment}')
    parts.append(_fmt_allows(mod))
    return '\n'.join(parts)

# %% ../nbs/00_core.ipynb #a486485f
def pyskills_dir():
    "Directory for user pyskills"
    return xdg_data_home() / 'pyskills'

def ensure_pyskills_dir():
    "Create xdg pyskills dir and .pth file if needed"
    sd = pyskills_dir()
    if sd.exists(): return
    sd.mkdir(parents=True)
    pth = Path(site.getsitepackages()[0]) / 'pyskills.pth'
    sd = str(sd)
    pth.write_text(sd + '\n')
    if sd not in sys.path: sys.path.append(sd)

# %% ../nbs/00_core.ipynb #2b3b357f
ensure_pyskills_dir()

# %% ../nbs/00_core.ipynb #553b1fbd
def clear_mod(prefix):
    "Clear modules starting with `prefix` from python caches"
    for k in list(sys.modules):
        if k.startswith(prefix): del sys.modules[k]
    importlib.invalidate_caches()

# %% ../nbs/00_core.ipynb #6ba14c44
def _pyskill_dist(name): return pyskills_dir() / f'{name.replace(".", "_")}-0.0.1.dist-info'

def enable_pyskill(name):
    "Enable pyskill `name` by creating its dist-info entry point"
    di = _pyskill_dist(name)
    di.mkdir(exist_ok=True)
    (di / 'METADATA').write_text(f'Name: {name.replace(".", "_")}\nVersion: 0.0.1\n')
    (di / 'entry_points.txt').write_text(f'[pyskills]\n{name} = {name}\n')
    clear_mod(name.split('.')[0])

def register_pyskill(name, docstr, code=''):
    "Register a pyskill module `name` in the xdg pyskills dir"
    sd = pyskills_dir()
    parts = name.split('.')
    mod_dir = sd / Path(*parts[:-1]) if len(parts) > 1 else sd
    mod_dir.mkdir(parents=True, exist_ok=True)
    for i in range(len(parts)-1): (sd / Path(*parts[:i+1]) / '__init__.py').touch()
    (mod_dir / f'{parts[-1]}.py').write_text(f'"""{docstr}"""\n{code}')
    enable_pyskill(name)

# %% ../nbs/00_core.ipynb #b80e18a8
def disable_pyskill(name):
    "Disable pyskill `name` by removing its dist-info entry point"
    di = _pyskill_dist(name)
    if di.exists(): shutil.rmtree(di)
    clear_mod(name.split('.')[0])

# %% ../nbs/00_core.ipynb #f74fdb5d
def delete_pyskill(name):
    "Delete pyskill `name` module files and dist-info"
    disable_pyskill(name)
    sd = pyskills_dir()
    parts = name.split('.')
    mod_file = sd / Path(*parts[:-1]) / f'{parts[-1]}.py' if len(parts) > 1 else sd / f'{parts[-1]}.py'
    if mod_file.exists(): mod_file.unlink()
