"""Skill discovery, LLM-friendly doc rendering, the allow registry, and pyskill registration

A plugin system allowing Python packages to register "skills" — units of LLM-usable functionality — via standard Python entry points. An LLM harness (e.g. solveit) discovers available pyskills without importing them, reads lightweight descriptions via AST inspection, and selectively loads chosen pyskills into context.

```python
def list_pyskills() -> dict[str, str]
```
Returns `{name: description}` for all registered pyskills, using `find_spec` + AST parsing — no imports.

```python
import mypackage.skill
```
Standard python native import

```python
doc(mypackage.skill)       # module overview: classes, functions, submodules
doc(SomeClass)             # class detail: bases, __init__, methods, properties
doc(some_func)             # function detail: full signature with docments
xdir(mypackage.skill)      # filtered names for public symbols
```
Inspect at increasing detail — works on any Python module, not just pyskills.

`allow` registers the callables a pyskill trusts to perform side-effecting operations under a sandbox (e.g. safepyrun): pass functions, `{cls: ['method']}` dicts (`...` for all public methods), or callable instances, and they land in the `__pytools__` registry; an object defining `__allow__` delegates registration to the items it returns. Outside a sandbox `allow` is a no-op, and inside one, sandboxed code can't broaden its own permissions, since `allow` itself raises an audit event.

`xdir` returns public names for a module, class, or instance. Modules respect `__all__` and include explicitly imported sibling submodules; classes include `__init__` and public methods; instances with a custom `__dir__` list their dynamic surface, and plain instances list their class's API. Pass `q` to filter the names with a case-insensitive regex.

A module with a very large API surface can set `__pyskill_sigs__ = False` to elide the types/functions listing from its `doc()` output: its docstring is then the whole answer, with one line noting the elision. Pass `all=True` to `doc` to list the elided symbols anyway.

A *package* with a substantive docstring — more than the default summary line plus docs link — is treated as curated, so `doc()` elides its mechanical submodule listing too: a curated package docstring, like the ones nbdev generates from a project's notebooks, already says which modules matter. `all=True` restores the listing:

A trailing `…` on an overview function line marks elided detail: the function has docments, or a docstring beyond its first line, so `doc(func)` will show more than the overview line did. A complete overview line instead ends with its bracketed doc key: the line already shows everything `doc(func)` would, so the key can be declared straight from the summary.

Pyskills can be added as standard modules with pyproject entrypoints. But for convenience, they can also be added to a custom pyskills XDG directory, which is automatically added to sys.path.

Docs: https://AnswerDotAI.github.io/pyskills/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['ep_desc', 'list_pyskills', 'allow', 'chk_dest', 'AllowPolicy', 'PosAllowPolicy', 'PathWritePolicy', 'OpenWritePolicy',
           'SymbolNotFound', 'resolve', 'xdir', 'doc', 'fmt_sig', 'docfind', 'pyskills_dir', 'ensure_pyskills_dir',
           'clear_mod', 'enable_pyskill', 'register_pyskill', 'disable_pyskill', 'delete_pyskill', '__pytools__']

# %% ../nbs/00_core.ipynb #38e384dc
from fastcore.utils import *
from fastcore.docments import MarkdownRenderer,can_render,docments
from fastcore.xdg import *
from importlib.metadata import entry_points
import builtins, importlib.util, types, inspect, collections, ast, site, shutil, sys, typing
from fastaudit.core import track_call

# %% ../nbs/00_core.ipynb #6dda45ba
def ep_desc(ep):
    "First paragraph of docstring for entry point `ep`, without importing it"
    try: spec = importlib.util.find_spec(ep.value.split(':')[0])
    except: return
    if not spec or not spec.origin: return None
    tree = ast.parse(Path(spec.origin).read_text())
    doc = ast.get_docstring(tree)
    if not doc: return None
    return doc.split('\n\n')[0]

# %% ../nbs/00_core.ipynb #d3233c49
@llmtool
def list_pyskills():
    """Returns {module: description} for all pyskills. To load a module, use `import {module}` then view `doc({module}).
    **NB**: pyskills are *THE* critical way to extend functionality. *ALWAYS* check for pyskills to help with tasks.
    If unsure whether a particular pyskill might help, load it and grabs its docs to see!"""
    return {ep.value: epd for ep in entry_points().select(group='pyskills') if (epd := ep_desc(ep)) is not None}

# %% ../nbs/00_core.ipynb #3c64526e
_all_ = ['__pytools__']

# %% ../nbs/00_core.ipynb #4e2a5e01
__pytools__ = collections.defaultdict(set)

def _set_wrapped(o, name, f=None):
    try:
        if f is None: f = getattr(o, name)
        if callable(f): setattr(o, name, track_call(f))
    except (AttributeError, TypeError): pass

# %% ../nbs/00_core.ipynb #a7f5fc60
def allow(*c, allow_policy=None): # Callable that raises if call not allowed
    "Add all items in `c` to `__pytools__`, optionally constrained by `allow_policy`"
    sys.audit('pyskills.allow', c)
    def _wrap(v):
        if allow_policy is None or v is ... or isinstance(v, tuple): return v
        return (v, allow_policy)
    added = []
    def _add(k, *vs):
        new = [v for v in vs if v not in __pytools__[k]]
        __pytools__[k].update(new)
        added.extend((k,v) for v in new)
    res = None
    for o in c:
        if hasattr(o, '__allow__'):
            allow(*o.__allow__(), allow_policy=allow_policy)
            res = o
            continue
        if isinstance(o, dict):
            for k,v in o.items():
                if callable(k) and not isinstance(k, (type, types.ModuleType)):
                    allow(k, allow_policy=v)
                    continue
                vals = listify(v)
                _add(k, *map(_wrap, vals))
                for x in vals:
                    if isinstance(name := x[0] if isinstance(x, tuple) else x, str): _set_wrapped(k, name)
        else:
            res = track_call(o) if callable(o) else o
            if not isinstance(o, type) and callable(o) and not inspect.isroutine(o) and not hasattr(o, '__qualname__'):
                _add(o, _wrap('__call__'))
                _set_wrapped(type(o), '__call__')
                continue
            objclass = getattr(o, '__objclass__', None)
            if objclass is not None:
                _add(objclass, _wrap(o.__name__))
                _set_wrapped(objclass, o.__name__, o)
                continue
            qualname = getattr(o, '__qualname__', '') or ''
            ow = inspect.unwrap(o) if callable(o) else o
            mod = sys.modules.get(getattr(ow, '__globals__', {}).get('__name__'
                ) or getattr(ow, '__module__', '__main__'), sys.modules.get('__main__'))
            if '.' in qualname:
                cls = getattr(mod, qualname.rsplit('.', 1)[0], None)
                if cls is not None:
                    _add(cls, _wrap(o.__name__))
                    _set_wrapped(cls, o.__name__, o)
                    continue
            _add(mod, _wrap(o.__name__))
            _set_wrapped(mod, o.__name__, o)
    if added: sys.audit('pyskills.allowed', added)
    if len(c)==1 and callable(c[0]): return res

# %% ../nbs/00_core.ipynb #a3124a91
def chk_dest(p, ok_dests):
    resolved = str(Path(p).expanduser().resolve())
    if not any(resolved == (rd := str(Path(d).expanduser().resolve())) or resolved.startswith(rd + '/') for d in ok_dests):
        raise PermissionError(f"Dest '{p}' not allowed; permitted: {ok_dests}")

# %% ../nbs/00_core.ipynb #59efbf64
class AllowPolicy:
    "Base for allow destination policies"
    def __call__(self, obj, args, kwargs, data): raise NotImplementedError

class PosAllowPolicy(AllowPolicy):
    "Check positional/keyword path arg is an allowed destination; non-path buffers/handles are skipped"
    def __init__(self, pos=0, kw=None): store_attr()
    def __call__(self, obj, args, kwargs, data):
        p = kwargs.get(self.kw) if self.kw and self.kw in kwargs else args[self.pos] if self.pos < len(args) else None
        if isinstance(p, bytes): p = os.fsdecode(p)
        if isinstance(p, (str, os.PathLike)): chk_dest(p, data['ok_dests'])

class PathWritePolicy(AllowPolicy):
    "Check resolved Path self, optionally also target args"
    def __init__(self, target_pos=None, target_kw=None): store_attr()
    def __call__(self, obj, args, kwargs, data):
        ok = data['ok_dests']
        chk_dest(obj, ok)
        if self.target_pos is not None and self.target_pos < len(args): chk_dest(args[self.target_pos], ok)
        if self.target_kw and self.target_kw in kwargs: chk_dest(kwargs[self.target_kw], ok)

class OpenWritePolicy(AllowPolicy):
    "Check open() only when mode is writable"
    def __call__(self, obj, args, kwargs, data):
        mode = kwargs.get('mode', args[1] if len(args) > 1 else 'r')
        if any(c in mode for c in 'wax+'): chk_dest(args[0] if args else kwargs.get('file'), data['ok_dests'])


# %% ../nbs/00_core.ipynb #533a79ab
class SymbolNotFound(Exception):
    def __repr__(self): return f"SymbolNotFound({self.args[0]})"
    __str__ = __repr__

def resolve(
    sym_nm:str,  # Dotted symbol path, with optional [n] indexing, e.g. "module.attr.subattr[1]"
):
    "Resolve a dotted symbol string to its Python object, with optional [n] indexing"
    if not isinstance(sym_nm, str): return sym_nm
    ns = vars(sys.modules['__main__'])
    obj = None
    for i,part in enumerate(re.split(r'\.(?![^\[]*\])', sym_nm.strip())):
        name,idx = re.match(r'(\w+)(?:\[(\d+)\])?$', part).groups()
        if i==0:
            if name in ns: obj = ns[name]
            else:
                try: obj = getattr(builtins, name)
                except AttributeError: raise SymbolNotFound(f"Symbol '{name}' not found.")
        else: obj = getattr(obj, name)
        if idx is not None: obj = obj[int(idx)]
    return obj

# %% ../nbs/00_core.ipynb #c21d33bf
def _is_own(sym, n):
    "Whether name `n` in module `sym` is an owned symbol or sibling submodule"
    m = getattr(sym, n, None)
    if m is None: return False
    if getattr(m, '__module__', None) == sym.__name__: return True
    return isinstance(m, types.ModuleType) and m.__name__.split('.')[0] == sym.__name__.split('.')[0]

# %% ../nbs/00_core.ipynb #67114fc7
def _imported_submods(sym):
    "Sibling submodules explicitly imported via `import pkg.sub` by module `sym`"
    pkg = sym.__name__.rsplit('.', 1)[0] if '.' in sym.__name__ else None
    if not pkg: return {}
    res = {}
    for node in ast.walk(ast.parse(inspect.getsource(sym))):
        if not isinstance(node, ast.Import): continue
        for alias in node.names:
            if alias.name.startswith(pkg + '.') and alias.name != sym.__name__:
                m = sys.modules.get(alias.name)
                if m: res[alias.asname or alias.name] = m
    return res

def _is_own(sym, n):
    "Whether name `n` in module `sym` is an owned symbol or sibling submodule"
    m = getattr(sym, n, None)
    if m is None: return False
    if getattr(m, '__module__', None) == sym.__name__: return True
    if not isinstance(m, types.ModuleType): return False
    mname = m.__name__
    if sym.__name__.startswith(mname + '.'): return False
    return mname.split('.')[0] == sym.__name__.split('.')[0]

# %% ../nbs/00_core.ipynb #a1ba52e3
def _dynamic(sym):
    "Does `sym`'s type define a custom `__dir__` (a dynamic API surface)?"
    return any('__dir__' in c.__dict__ for c in type(sym).__mro__[:-1])

def _xdir(sym):
    "Filtered (name, obj) pairs for public symbols of a module or class (or anything with `__dir__`)"
    if isinstance(sym, types.ModuleType):
        names = getattr(sym, '__all__', None)
        if names is None: names = [n for n in sorted(dir(sym)) if not n.startswith('_') and _is_own(sym, n)]
        res = [(n, getattr(sym, n)) for n in names if getattr(sym, n, None) is not None]
        subs = _imported_submods(sym)
        return res + [(n, m) for n,m in sorted(subs.items()) if n not in dict(res)]
    if isinstance(sym, type):
        res = []
        init = getattr(sym, '__init__', None)
        if init and init is not object.__init__: res.append(('__init__', init))
        return res + [(n, v) for n,v in sorted(sym.__dict__.items()) if not n.startswith('_')]
    if not _dynamic(sym): return []
    return [(n, getattr(sym, n, None)) for n in sorted(dir(sym)) if not n.startswith('_')]

@allow
def xdir(
    sym:str|object, # Module, class, or instance to inspect
    q:str=None # Optional case-insensitive regex over names
):
    "Filtered names for public symbols of a module, class, or instance (a plain instance lists its class)"
    if isinstance(sym, str): sym = resolve(sym)
    if not isinstance(sym, (types.ModuleType, type)) and not _dynamic(sym): sym = type(sym)
    res = [o for o,_ in _xdir(sym)]
    return [o for o in res if re.search(q, o, re.I)] if q else res

# %% ../nbs/00_core.ipynb #15e66852
def _doc1(sym, all=False):
    if isinstance(sym, str): sym = resolve(sym)
    if isinstance(sym, types.ModuleType): return _doc_module(sym, all)
    try:
        if isinstance(sym, type) and getattr(sym, '__name__', ''): return PrettyString(_doc_class(sym))
        if hasattr(sym, '_repr_markdown_'): return PrettyString(sym._repr_markdown_())
        if callable(sym) and can_render(sym): return PrettyString(MarkdownRenderer(sym))
    except Exception as e:
        ds = inspect.cleandoc(getattr(sym, '__doc__', None) or '')
        return PrettyString(f'{ds}\n(doc render failed: {type(e).__name__}: {e}; stale kernel? try a restart)'.strip())
    if (items := _xdir(sym)): return _doc_instance(sym, items)
    if '__str__' in type(sym).__dict__: return str(sym)
    if '__repr__' in type(sym).__dict__: return repr(sym)
    return PrettyString(MarkdownRenderer(sym))

@allow
def doc(
    sym:str|object,   # Object (or dotted name) to document
    *syms:str|object,  # More objects: each doc appended as its own blank-line-separated section
    all:bool=False    # Show symbol listings elided by `__pyskill_sigs__=False`?
)->str:
    "Docstring of modules, classes, functions, instances or any other Python objects."
    return PrettyString('\n\n'.join(str(_doc1(s, all)) for s in (sym, *syms)))


# %% ../nbs/00_core.ipynb #90aae7aa
class _N:
    def __init__(self,s): self.s=s
    def __repr__(self): return self.s

def _fmt_ann(a):
    if a is inspect._empty: return a
    if isinstance(a, type): return a.__name__
    o,args = typing.get_origin(a),typing.get_args(a)
    if o is None: return getattr(a, '__name__', None) or str(a)
    if o in (types.UnionType, typing.Union): return ' | '.join(_fmt_ann(x) for x in args)
    on = getattr(o, '__name__', None) or str(o)
    return f"{on}[{', '.join(_fmt_ann(x) for x in args)}]"

def _ann(a): return _N(_fmt_ann(a)) if a is not inspect._empty else a

def fmt_sig(f, ps=None):
    try: s = signature_ex(f)
    except (ValueError, TypeError): return '(...)'
    ps = [p.replace(annotation=_ann(p.annotation)) for p in (s.parameters.values() if ps is None else ps)]
    return str(s.replace(parameters=ps, return_annotation=_ann(s.return_annotation)))

# %% ../nbs/00_core.ipynb #ae0c509a
def _fmt_method(name, method, prefix=''):
    sig = fmt_sig(method)
    d = getattr(method, '__doc__', None)
    res = f'    {prefix}def {name}{sig}: ...'
    if d and name != '__init__': res += f'  # {d.splitlines()[0].strip()}'
    return res

def _doc_class(sym):
    bases = ','.join(b.__name__ for b in sym.__mro__[1:-1]) if sym.__mro__[1:-1] else ''
    parts = [f'class {sym.__name__}({bases}):' if bases else f'class {sym.__name__}:']
    for name,raw in _xdir(sym):
        if isinstance(raw, property): parts.append(_fmt_method(name, raw.fget, '@property\n    '))
        elif isinstance(raw, classmethod): parts.append(_fmt_method(name, raw.__func__, '@classmethod\n    '))
        elif isinstance(raw, staticmethod): parts.append(_fmt_method(name, raw.__func__, '@staticmethod\n    '))
        elif callable(raw): parts.append(_fmt_method(name, raw))
    d = sym.__doc__ or (getattr(sym, '__init__', None) and sym.__init__.__doc__)
    if d: parts.insert(1, '    """' + inspect.cleandoc(d).replace('\n', '\n    ') + '"""')
    return PrettyString(parts[0] + '\n' + '\n'.join(parts[1:]))

# %% ../nbs/00_core.ipynb #b2b29e28
def _elided(obj, d):
    "Does `doc(obj)` show more than its overview line: docments, or a docstring beyond its first line?"
    if any(l.strip() for l in d[1:]): return True
    try: return any(v is not None for v in docments(obj).values())
    except Exception: return False

def _doc_module(mod, all=False):
    parts = [f'# module {mod.__name__}:\n']
    if mod.__doc__: parts.append(f'"""{inspect.cleandoc(mod.__doc__)}\n"""')
    groups,refs = getattr(mod, '__pyskill_params__', {}),{}
    typs,funcs,subs = [],[],[]
    for name,obj in _xdir(mod):
        ds = getattr(obj, '__doc__', None)
        if not ds and isinstance(obj, type): ds = getattr(getattr(obj, '__init__', None), '__doc__', None)
        d = (ds or '').splitlines()
        comment = f': ...  # {d[0].strip()}' if d and d[0].strip() else ''
        if isinstance(obj, types.ModuleType): subs.append(f'  {name}{comment}')
        elif isinstance(obj, type):
            bases = [b.__name__ for b in obj.__mro__[1:-1]]
            if len(bases)>3: bases = bases[:3]+['…']
            bases = ','.join(bases)
            base_str = f'({bases})' if bases else ''
            typs.append(f'- class {name}{base_str}{comment}')
        elif callable(obj):
            pre = 'async def' if inspect.iscoroutinefunction(obj) else 'def'
            if _elided(obj, d): comment = f'{comment}…' if comment else ': …  # …'
            sig = (groups and _grouped_sig(obj, name, groups, refs)) or fmt_sig(obj)
            funcs.append(f'- {pre} {name}{sig}{comment}')
    if not all and not getattr(mod, '__pyskill_sigs__', True):
        parts.append(f"\n## elided: {len(typs)} types, {len(funcs)} functions. `doc('{mod.__name__}', all=True)` lists them.")
        typs = funcs = refs = ()
    if typs: parts += ['\n## types:', *typs]
    if funcs: parts += ['\n## functions:', *funcs]
    if refs:
        parts.append('\n## shared params:')
        for g,r in refs.items(): parts += _fmt_group(g, *r)
    if subs and not all and len(inspect.cleandoc(mod.__doc__ or '').splitlines())>3:
        parts.append(f"\n## elided: {len(subs)} submodules. `doc('{mod.__name__}', all=True)` lists them.")
        subs = ()
    if subs: parts += ['\n## submodules:', *subs]
    return PrettyString('\n'.join(parts))

# %% ../nbs/00_core.ipynb #155cdb61
def _grouped_sig(f, name, groups, refs):
    "Signature of `f` with each fully-matched param group collapsed to `**group`, recording each group's first match in `refs`"
    try: ps = list(signature_ex(f).parameters.values())
    except (ValueError, TypeError): return None
    done = []
    for g,names in groups.items():
        gp = {p.name: p for p in ps if p.name in names}
        if len(gp) < len(names): continue
        gname,_,ref = refs.setdefault(g, (name, f, [gp[n] for n in names]))
        if any(gp[n].annotation != r.annotation or gp[n].default != r.default for n,r in zip(names, ref)):
            warnings.warn(f"`{name}` group `{g}` params differ from `{gname}`; rendering inline")
            continue
        ps = [p for p in ps if p.name not in names]
        done.append(g)
    if not done: return None
    ps += [inspect.Parameter(g, inspect.Parameter.VAR_KEYWORD) for g in done]
    try: return fmt_sig(f, ps)
    except ValueError: return None

def _fmt_group(g, name, f, ps):
    "`## shared params:` lines for group `g`: its params with docments, from first matching function `name`"
    try: dm = docments(f)
    except Exception: dm = {}
    lines = [f'- **{g} (from `{name}`):']
    lines += [f"    {p.replace(annotation=_ann(p.annotation))}," + (f' # {c}' if (c := dm.get(p.name)) else '') for p in ps]
    return lines

# %% ../nbs/00_core.ipynb #ccca39db
def _doc_instance(sym, items):
    parts = [f'Instance of type {type(sym).__name__}:']
    for name,obj in items:
        ds = (getattr(obj, '__doc__', None) or '').splitlines()
        comment = f'  # {ds[0].strip()}' if ds and ds[0].strip() else ''
        if callable(obj):
            try: sig = str(signature_ex(obj))
            except (ValueError, TypeError): sig = '(...)'
            parts.append(f'- {name}{sig}{comment}')
        else: parts.append(f'- {name}: {type(obj).__name__} = {repr(obj)[:80]}')
    return PrettyString('\n'.join(parts))

# %% ../nbs/00_core.ipynb #c22af8b2
@allow
def docfind(o:str|object, q:str, n:int=2, _pre:str=''):
    "Search `doc()` recursively through `xdir(o)`, looking at submodules, classes, and functions, to depth `n`"
    pat = re.compile(q, re.IGNORECASE)
    res = []
    if isinstance(o, str): o = resolve(o)
    try: d = doc(o) or ''
    except: d = ''
    if pat.search(d): res.append(_pre + ' // ' + d.split('\n')[0])
    if n > 0:
        for k in xdir(o):
            try: child = getattr(o, k)
            except: continue
            nm = f'{_pre}.{k}' if _pre else k
            res += docfind(child, q, n-1, nm)
    return res

# %% ../nbs/00_core.ipynb #a486485f
def pyskills_dir():
    "Directory for user pyskills"
    return xdg_data_home() / 'pyskills'

def ensure_pyskills_dir():
    "Create xdg pyskills dir and .pth file if needed"
    sd = str(pyskills_dir())
    if sd in sys.path: return
    Path(sd).mkdir(parents=True, exist_ok=True)
    sps = site.getsitepackages()
    try: sps.append(site.getusersitepackages())
    except AttributeError: pass
    for sp in sps:
        pth = Path(sp) / 'pyskills.pth'
        if pth.exists() and sd in pth.read_text(): break
        try:
            Path(sp).mkdir(parents=True, exist_ok=True)
            pth.write_text(sd + '\n')
            break
        except (PermissionError, OSError): pass
    sys.path.append(sd)

# %% ../nbs/00_core.ipynb #2b3b357f
ensure_pyskills_dir()

# %% ../nbs/00_core.ipynb #553b1fbd
def clear_mod(prefix):
    "Clear modules starting with `prefix` from python caches"
    for k in list(sys.modules):
        if k.startswith(prefix): del sys.modules[k]
    importlib.invalidate_caches()

# %% ../nbs/00_core.ipynb #6ba14c44
def _pyskill_dist(name): return pyskills_dir() / f'{name.replace(".", "_")}-0.0.1.dist-info'

def enable_pyskill(name):
    "Enable pyskill `name` by creating its dist-info entry point"
    di = _pyskill_dist(name)
    di.mkdir(exist_ok=True)
    (di / 'METADATA').write_text(f'Name: {name.replace(".", "_")}\nVersion: 0.0.1\n')
    (di / 'entry_points.txt').write_text(f'[pyskills]\n{name} = {name}\n')
    clear_mod(name.split('.')[0])

def register_pyskill(name, docstr, code=''):
    "Register a pyskill module `name` in the xdg pyskills dir"
    sd = pyskills_dir()
    parts = name.split('.')
    mod_dir = sd / Path(*parts[:-1]) if len(parts) > 1 else sd
    mod_dir.mkdir(parents=True, exist_ok=True)
    for i in range(len(parts)-1): (sd / Path(*parts[:i+1]) / '__init__.py').touch()
    (mod_dir / f'{parts[-1]}.py').write_text(f'"""{docstr}"""\n{code}')
    enable_pyskill(name)

# %% ../nbs/00_core.ipynb #b80e18a8
def disable_pyskill(name):
    "Disable pyskill `name` by removing its dist-info entry point"
    di = _pyskill_dist(name)
    if di.exists(): shutil.rmtree(di)
    clear_mod(name.split('.')[0])

# %% ../nbs/00_core.ipynb #1e4f4c4c
def delete_pyskill(name):
    "Delete pyskill `name` module files and dist-info"
    disable_pyskill(name)
    sd = pyskills_dir()
    parts = name.split('.')
    mod_file = sd / Path(*parts[:-1]) / f'{parts[-1]}.py' if len(parts) > 1 else sd / f'{parts[-1]}.py'
    if mod_file.exists(): mod_file.unlink()
