"""Skill discovery, LLM-friendly doc rendering, the allow registry, and pyskill registration

A pyskill is a Python module that gives an LLM instructions or functions to use. Packages register these modules through Python entry points. A host such as Solveit first shows the LLM a catalogue of short descriptions. It reads those descriptions from source without loading the skill. The LLM then chooses which modules to import and read in full.

`list_pyskills()` returns a dictionary of module paths and descriptions. It locates each source file with `find_spec_noimport` and reads its docstring with Python's AST parser.

After choosing a skill, import it and read its documentation:

```python
import mypackage.skill
doc(mypackage.skill)       # Overview of classes, functions, and submodules
doc(SomeClass)            # Bases, constructor, methods, and properties
doc(some_func)            # Full signature and parameter docments
xdir(mypackage.skill)     # Public names
```

These inspection functions work on any Python module, not just pyskills.

Use `allow` to register trusted functions, class methods, or callable instances in `__pytools__`. A dictionary such as `{cls: ['method']}` selects methods by name. Use `...` to select all public methods. A group object can return its operations from `__allow__`.

Registration is a permission request, not sandbox enforcement. `allow` emits a `pyskills.allow` audit event before making changes. A sandbox must reject that event if untrusted code tries to expand its permissions. Without an audit handler that rejects the event, registration proceeds.

Use `xdir` to find public names before asking for their documentation. For a module, it uses `__all__` when present. Otherwise it lists the module's own definitions and sibling submodules, excluding imports from unrelated packages. It also includes explicitly imported sibling submodules in either case.

For a class, it lists public members and a non-default constructor. A plain instance uses its class's listing. An instance with a custom `__dir__` supplies its dynamic names instead. Pass `q` to filter the list with a case-insensitive regular expression.

An overview line ending in `…` has more documentation than it shows. Read `doc(callable)` before using that operation to see its parameter docments and remaining docstring.

Class and namespace overviews inspect properties without evaluating them. An object's custom `_repr_markdown_` supplies its own display, including generated API documentation or a data-oriented result view.

Set `__pyskill_sigs__ = False` when a module's type and function listings are too large for its overview. `doc()` keeps the docstring and reports how many entries it omitted. Pass `all=True` to include those entries.

A package docstring can explain which submodules a reader needs, as nbdev's generated package documentation does. When the cleaned docstring has more than three lines, `doc()` hides the automatic submodule list. A default summary and documentation link do not meet that threshold. Pass `all=True` to show the list.

You don't need to build a package to add a personal pyskill. Put its module in the user pyskills directory under XDG data home. Pyskills adds that directory to `sys.path`. Package entry points remain an option for skills you distribute with a library.

Call `enable_local_skills(folder)` when opening a dialog to find skills near that folder. It searches `PYSKILLs/` in the opening folder and each ancestor. Public top-level `.py` files and packages supply skill entry points. A package uses its `__init__.py` as the skill module. Its other modules remain ordinary implementation modules. Names starting with an underscore are private.

The nearest folder wins when local folders contain the same name. A name that conflicts with an import outside those folders raises an error instead of replacing that import.

The opening folder stays fixed after `chdir`. Discovery rescans those locations for new files without executing skill code or writing metadata files. Imports still use Python's module cache. Repeating activation for the same folder returns the existing finder. Use a fresh kernel to activate a different folder.

Docs: https://AnswerDotAI.github.io/pyskills/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['find_spec_noimport', 'ep_desc', 'list_pyskills', 'allow', 'chk_dest', 'AllowPolicy', 'PosAllowPolicy',
           'PathWritePolicy', 'OpenWritePolicy', 'SymbolNotFound', 'resolve', 'xdir', 'doc', 'fmt_sig', 'docfind',
           'pyskills_dir', 'ensure_pyskills_dir', 'clear_mod', 'enable_pyskill', 'register_pyskill', 'disable_pyskill',
           'delete_pyskill', 'enable_local_skills', '__pytools__']

# %% ../nbs/00_core.ipynb #38e384dc
from fastcore.utils import *
from fastcore.docments import MarkdownRenderer,can_render,docments,docstring,ann_parts
from fastcore.xdg import *
from importlib.metadata import entry_points
from importlib.machinery import ModuleSpec
from pkgutil import get_importer
import builtins, importlib.util, types, inspect, collections, ast, site, shutil, sys, typing, textwrap
from fastaudit.core import track_call

# %% ../nbs/00_core.ipynb #3ec024c7
from fastcore.basics import _clsmethod

# %% ../nbs/00_core.ipynb #9601d87c
def _find_child_spec(name, paths):
    locations = []
    for path in paths:
        finder = get_importer(path)
        if finder is None or (spec := finder.find_spec(name)) is None: continue
        if spec.loader is not None: return spec
        locations.extend(spec.submodule_search_locations or [])
    if locations:
        spec = ModuleSpec(name, None, is_package=True)
        spec.submodule_search_locations = locations
        return spec

def find_spec_noimport(name:str):
    "Find the spec for an absolute module name without importing its parents"
    root, *parts = name.split('.')
    spec = importlib.util.find_spec(root)
    for part in parts:
        if spec is None or not spec.submodule_search_locations: return None
        root += '.' + part
        spec = _find_child_spec(root, spec.submodule_search_locations)
    return spec


# %% ../nbs/00_core.ipynb #6dda45ba
def ep_desc(ep):
    "First paragraph of docstring for entry point `ep`, without importing it"
    try: spec = find_spec_noimport(ep.value.split(':')[0])
    except: return
    if not spec or not spec.origin: return None
    tree = ast.parse(Path(spec.origin).read_text())
    doc = ast.get_docstring(tree)
    if not doc: return None
    return doc.split('\n\n')[0]

# %% ../nbs/00_core.ipynb #d3233c49
@llmtool
def list_pyskills():
    """Returns {module: description} for all pyskills. To load a module, use `import {module}` then view `doc({module}).
    **NB**: pyskills are *THE* critical way to extend functionality. *ALWAYS* check for pyskills to help with tasks.
    If unsure whether a particular pyskill might help, load it and grabs its docs to see!"""
    return {ep.value: epd for ep in entry_points().select(group='pyskills') if (epd := ep_desc(ep)) is not None}

# %% ../nbs/00_core.ipynb #3c64526e
_all_ = ['__pytools__']

__pytools__ = collections.defaultdict(set)

def _set_wrapped(o, name, f=None):
    try:
        if f is None: f = getattr(o, name)
        if callable(f): setattr(o, name, track_call(f))
    except (AttributeError, TypeError): pass

# %% ../nbs/00_core.ipynb #a7f5fc60
def allow(*c, allow_policy=None): # Callable that raises if call not allowed
    "Add all items in `c` to `__pytools__`, optionally constrained by `allow_policy`"
    sys.audit('pyskills.allow', c)
    def _wrap(v):
        if allow_policy is None or v is ... or isinstance(v, tuple): return v
        return (v, allow_policy)
    res = None
    for o in c:
        if hasattr(o, '__allow__'):
            allow(*o.__allow__(), allow_policy=allow_policy)
            res = o
            continue
        if isinstance(o, dict):
            for k,v in o.items():
                if callable(k) and not isinstance(k, (type, types.ModuleType)):
                    allow(k, allow_policy=v)
                    continue
                vals = listify(v)
                __pytools__[k].update(_wrap(x) for x in vals)
                for x in vals:
                    if isinstance(name := x[0] if isinstance(x, tuple) else x, str): _set_wrapped(k, name)
        else:
            res = track_call(o) if callable(o) else o
            if not isinstance(o, type) and callable(o) and not inspect.isroutine(o) and not hasattr(o, '__qualname__'):
                __pytools__[o].add(_wrap('__call__'))
                _set_wrapped(type(o), '__call__')
                continue
            objclass = getattr(o, '__objclass__', None)
            if objclass is not None:
                __pytools__[objclass].add(_wrap(o.__name__))
                _set_wrapped(objclass, o.__name__, o)
                continue
            qualname = getattr(o, '__qualname__', '') or ''
            ow = inspect.unwrap(o) if callable(o) else o
            mod = sys.modules.get(getattr(ow, '__globals__', {}).get('__name__'
                ) or getattr(ow, '__module__', '__main__'), sys.modules.get('__main__'))
            if '.' in qualname:
                cls = getattr(mod, qualname.rsplit('.', 1)[0], None)
                if cls is not None:
                    __pytools__[cls].add(_wrap(o.__name__))
                    _set_wrapped(cls, o.__name__, o)
                    continue
            __pytools__[mod].add(_wrap(o.__name__))
            _set_wrapped(mod, o.__name__, o)
    if len(c)==1 and callable(c[0]): return res

# %% ../nbs/00_core.ipynb #a3124a91
def chk_dest(p, ok_dests):
    if ok_dests is None: return
    resolved = str(Path(p).expanduser().resolve())
    if not any(resolved == (rd := str(Path(d).expanduser().resolve())) or resolved.startswith(rd + '/') for d in ok_dests):
        raise PermissionError(f"Dest '{p}' not allowed; permitted: {ok_dests}")

# %% ../nbs/00_core.ipynb #59efbf64
class AllowPolicy:
    "Base for allow destination policies"
    def __call__(self, obj, args, kwargs, data): raise NotImplementedError

class PosAllowPolicy(AllowPolicy):
    "Check positional/keyword path arg is an allowed destination; non-path buffers/handles are skipped"
    def __init__(self, pos=0, kw=None): store_attr()
    def __call__(self, obj, args, kwargs, data):
        p = kwargs.get(self.kw) if self.kw and self.kw in kwargs else args[self.pos] if self.pos < len(args) else None
        if isinstance(p, bytes): p = os.fsdecode(p)
        if isinstance(p, (str, os.PathLike)): chk_dest(p, data['ok_dests'])

# %% ../nbs/00_core.ipynb #798a382c
class PathWritePolicy(AllowPolicy):
    "Check resolved Path self, optionally also target args"
    def __init__(self, target_pos=None, target_kw=None): store_attr()
    def __call__(self, obj, args, kwargs, data):
        ok = data['ok_dests']
        chk_dest(obj, ok)
        if self.target_pos is not None and self.target_pos < len(args): chk_dest(args[self.target_pos], ok)
        if self.target_kw and self.target_kw in kwargs: chk_dest(kwargs[self.target_kw], ok)

# %% ../nbs/00_core.ipynb #d5e5b500
class OpenWritePolicy(AllowPolicy):
    "Check open() only when mode is writable"
    def __call__(self, obj, args, kwargs, data):
        mode = kwargs.get('mode', args[1] if len(args) > 1 else 'r')
        if any(c in mode for c in 'wax+'): chk_dest(args[0] if args else kwargs.get('file'), data['ok_dests'])

# %% ../nbs/00_core.ipynb #533a79ab
class SymbolNotFound(Exception):
    def __repr__(self): return f"SymbolNotFound({self.args[0]})"
    __str__ = __repr__

def resolve(
    sym_nm:str,  # Dotted symbol path, with optional [n] indexing, e.g. "module.attr.subattr[1]"
):
    "Resolve a dotted symbol string to its Python object, with optional [n] indexing"
    if not isinstance(sym_nm, str): return sym_nm
    ns = vars(sys.modules['__main__'])
    obj = None
    for i,part in enumerate(re.split(r'\.(?![^\[]*\])', sym_nm.strip())):
        name,idx = re.match(r'(\w+)(?:\[(\d+)\])?$', part).groups()
        if i==0:
            if name in ns: obj = ns[name]
            else:
                try: obj = getattr(builtins, name)
                except AttributeError: raise SymbolNotFound(f"Symbol '{name}' not found.")
        else: obj = getattr(obj, name)
        if idx is not None: obj = obj[int(idx)]
    return obj

# %% ../nbs/00_core.ipynb #67114fc7
def _imported_submods(sym):
    "Sibling submodules explicitly imported via `import pkg.sub` by module `sym`"
    pkg = sym.__name__.rsplit('.', 1)[0] if '.' in sym.__name__ else None
    if not pkg: return {}
    res = {}
    for node in ast.walk(ast.parse(inspect.getsource(sym))):
        if not isinstance(node, ast.Import): continue
        for alias in node.names:
            if alias.name.startswith(pkg + '.') and alias.name != sym.__name__:
                m = sys.modules.get(alias.name)
                if m: res[alias.asname or alias.name] = m
    return res

def _is_own(sym, n):
    "Whether name `n` in module `sym` is an owned symbol or sibling submodule"
    m = getattr(sym, n, None)
    if m is None: return False
    if getattr(m, '__module__', None) == sym.__name__: return True
    if not isinstance(m, types.ModuleType): return False
    mname = m.__name__
    if sym.__name__.startswith(mname + '.'): return False
    return mname.split('.')[0] == sym.__name__.split('.')[0]

# %% ../nbs/00_core.ipynb #a1ba52e3
def _dynamic(sym):
    "Does `sym`'s type define a custom `__dir__` (a dynamic API surface)?"
    return any('__dir__' in c.__dict__ for c in type(sym).__mro__[:-1])

def _xnames(sym):
    if isinstance(sym, types.ModuleType):
        names = getattr(sym, '__all__', None)
        if names is None: names = [n for n in sorted(dir(sym)) if not n.startswith('_') and _is_own(sym, n)]
        return list(dict.fromkeys([*names, *_imported_submods(sym)]))
    if isinstance(sym, type):
        names = [n for n in sorted(vars(sym)) if not n.startswith('_')]
        if getattr(sym, '__init__', object.__init__) is not object.__init__: names.insert(0, '__init__')
        return names
    if not _dynamic(sym): return _xnames(type(sym))
    return sorted({n for n in dir(sym) if not n.startswith('_')})

@allow
def xdir(
    sym:str|object, # Module, class, or instance to inspect
    q:str=None # Optional case-insensitive regex over names
):
    "Public names without evaluating instance properties; a plain instance lists its class's names"
    if isinstance(sym, str): sym = resolve(sym)
    names = _xnames(sym)
    return [n for n in names if re.search(q, n, re.I)] if q else names

# %% ../nbs/00_core.ipynb #058d53d8
def _member(sym, name):
    raw = inspect.getattr_static(sym, name, None)
    if inspect.isdatadescriptor(raw): return raw
    return getattr(sym, name)

def _xdir(sym):
    "Public members, retaining data descriptors without evaluating them"
    if isinstance(sym, types.ModuleType):
        subs = _imported_submods(sym)
        return [(n, subs[n] if n in subs else getattr(sym, n)) for n in _xnames(sym)]
    if isinstance(sym, type): return [(n, inspect.getattr_static(sym, n)) for n in _xnames(sym)]
    return [(n, _member(sym, n)) for n in _xnames(sym)]

# %% ../nbs/00_core.ipynb #15e66852
def _doc1(sym, all=False):
    if isinstance(sym, str): sym = resolve(sym)
    if isinstance(sym, types.ModuleType): return _doc_module(sym, all)
    try:
        if isinstance(sym, type) and getattr(sym, '__name__', ''): return PrettyString(_doc_class(sym))
        if hasattr(sym, '_repr_markdown_'): return PrettyString(sym._repr_markdown_())
        if _dynamic(sym): return _doc_instance(sym, _xdir(sym))
        if callable(sym) and can_render(sym): return PrettyString(MarkdownRenderer(sym))
    except Exception as e: return PrettyString(f'{docstring(sym)}\n(doc render failed: {type(e).__name__}: {e})'.strip())
    if '__str__' in type(sym).__dict__: return str(sym)
    if '__repr__' in type(sym).__dict__: return repr(sym)
    return PrettyString(MarkdownRenderer(sym))

@allow
def doc(
    sym:str|object,   # Object (or dotted name) to document; use the instance for a generated or bound API
    *syms:str|object,  # More objects: each doc appended as its own blank-line-separated section
    all:bool=False    # Show symbol listings elided by `__pyskill_sigs__=False`?
)->str:
    "Full callable documentation or a module/class/namespace overview; custom Markdown displays are preserved"
    return PrettyString('\n\n'.join(str(_doc1(s, all)) for s in (sym, *syms)))

# %% ../nbs/00_core.ipynb #90aae7aa
class _N:
    def __init__(self,s): self.s=s
    def __repr__(self): return self.s

def _fmt_ann(a):
    if a is inspect._empty: return a
    a = ann_parts(a)[0]
    if isinstance(a, type): return a.__name__
    o,args = typing.get_origin(a),typing.get_args(a)
    if o is None: return getattr(a, '__name__', None) or str(a)
    if o in (types.UnionType, typing.Union): return ' | '.join(_fmt_ann(x) for x in args)
    on = getattr(o, '__name__', None) or str(o)
    return f"{on}[{', '.join(_fmt_ann(x) for x in args)}]"

def _ann(a): return _N(_fmt_ann(a)) if a is not inspect._empty else a

# %% ../nbs/00_core.ipynb #3669a5e6
def fmt_sig(f, ps=None):
    try: s = signature_ex(f)
    except (ValueError, TypeError): return '(...)'
    ps = [p.replace(annotation=_ann(p.annotation)) for p in (s.parameters.values() if ps is None else ps)]
    return str(s.replace(parameters=ps, return_annotation=_ann(s.return_annotation)))

# %% ../nbs/00_core.ipynb #b2b29e28
def _elided(obj, d):
    "Does `doc(obj)` show more than its overview line: docments, or a docstring beyond its first line?"
    if any(l.strip() for l in d[1:]): return True
    try: return any(v is not None for v in docments(obj).values())
    except Exception: return False

def _fmt_method(name, method, prefix=''):
    sig = fmt_sig(method)
    d = docstring(method).splitlines()
    pre = 'async def' if is_async_callable(method) else 'def'
    res = f'    {prefix}{pre} {name}{sig}: ...'
    if d and name != '__init__': res += f'  # {d[0].strip()}'
    if _elided(method, d): res += '…'
    return res

def _doc_class(sym):
    bases = ','.join(b.__name__ for b in sym.__mro__[1:-1]) if sym.__mro__[1:-1] else ''
    parts = [f'class {sym.__name__}({bases}):' if bases else f'class {sym.__name__}:']
    for name,raw in _xdir(sym):
        if isinstance(raw, property): parts.append(_fmt_method(name, raw.fget, '@property\n    '))
        elif isinstance(raw, (classmethod, _clsmethod)): parts.append(_fmt_method(name, getattr(sym, name), '@classmethod\n    '))
        elif isinstance(raw, staticmethod): parts.append(_fmt_method(name, raw.__func__, '@staticmethod\n    '))
        elif name=='__init__' and can_render(raw): parts.append(textwrap.indent(str(MarkdownRenderer(raw)), '    '))
        elif callable(raw): parts.append(_fmt_method(name, raw))
    d = inspect.getdoc(sym)
    if d: parts.insert(1, '    """' + inspect.cleandoc(d).replace('\n', '\n    ') + '"""')
    if bases: parts.append('\nInherited members: ' + ', '.join(f'`doc({b.__name__})`' for b in sym.__bases__ if b is not object) + '.')
    parts.append('\nOverview only. Read `doc(Class.member)` for entries marked …; use an instance for dynamically bound members.')
    return PrettyString('\n'.join(parts))

# %% ../nbs/00_core.ipynb #c10c4f82
def _doc_module(mod, all=False):
    parts = [f'# module {mod.__name__}:\n']
    if mod.__doc__: parts.append(f'"""{inspect.cleandoc(mod.__doc__)}\n"""')
    groups,refs = getattr(mod, '__pyskill_params__', {}),{}
    typs,funcs,subs = [],[],[]
    for name,obj in _xdir(mod):
        d = docstring(obj).splitlines()
        comment = f': ...  # {d[0].strip()}' if d and d[0].strip() else ''
        if isinstance(obj, types.ModuleType): subs.append(f'  {name}{comment}')
        elif isinstance(obj, type):
            bases = [b.__name__ for b in obj.__mro__[1:-1]]
            if len(bases)>3: bases = bases[:3]+['…']
            bases = ','.join(bases)
            base_str = f'({bases})' if bases else ''
            typs.append(f'- class {name}{base_str}{comment}')
        elif callable(obj):
            pre = 'async def' if is_async_callable(obj) else 'def'
            if _elided(obj, d): comment = f'{comment}…' if comment else ': …  # …'
            sig = (groups and _grouped_sig(obj, name, groups, refs)) or fmt_sig(obj)
            funcs.append(f'- {pre} {name}{sig}{comment}')
    if not all and not getattr(mod, '__pyskill_sigs__', True):
        parts.append(f"\n## elided: {len(typs)} types, {len(funcs)} functions. `doc('{mod.__name__}', all=True)` lists them.")
        typs = funcs = refs = ()
    if typs: parts += ['\n## types:', *typs]
    if funcs: parts += ['\n## functions:', *funcs]
    if refs:
        parts.append('\n## shared params:')
        for g,r in refs.items(): parts += _fmt_group(g, *r)
    if subs and not all and len(inspect.cleandoc(mod.__doc__ or '').splitlines())>3:
        parts.append(f"\n## elided: {len(subs)} submodules. `doc('{mod.__name__}', all=True)` lists them.")
        subs = ()
    if subs: parts += ['\n## submodules:', *subs]
    return PrettyString('\n'.join(parts))

# %% ../nbs/00_core.ipynb #155cdb61
def _grouped_sig(f, name, groups, refs):
    "Signature of `f` with each fully-matched param group collapsed to `**group`, recording each group's first match in `refs`"
    try: ps = list(signature_ex(f).parameters.values())
    except (ValueError, TypeError): return None
    done = []
    for g,names in groups.items():
        gp = {p.name: p for p in ps if p.name in names}
        if len(gp) < len(names): continue
        gname,_,ref = refs.setdefault(g, (name, f, [gp[n] for n in names]))
        if any(gp[n].annotation != r.annotation or gp[n].default != r.default for n,r in zip(names, ref)):
            warnings.warn(f"`{name}` group `{g}` params differ from `{gname}`; rendering inline")
            continue
        ps = [p for p in ps if p.name not in names]
        done.append(g)
    if not done: return None
    ps += [inspect.Parameter(g, inspect.Parameter.VAR_KEYWORD) for g in done]
    try: return fmt_sig(f, ps)
    except ValueError: return None

def _fmt_group(g, name, f, ps):
    "`## shared params:` lines for group `g`: its params with docments, from first matching function `name`"
    try: dm = docments(f)
    except Exception: dm = {}
    lines = [f'- **{g} (from `{name}`):']
    lines += [f"    {p.replace(annotation=_ann(p.annotation))}," + (f' # {c}' if (c := dm.get(p.name)) else '') for p in ps]
    return lines

# %% ../nbs/00_core.ipynb #ccca39db
def _doc_instance(sym, items):
    parts = [f'Instance of type {type(sym).__name__}:']
    if d := docstring(type(sym) if callable(sym) else sym): parts.append(d)
    if callable(sym): parts.append(_fmt_method('__call__', sym).strip())
    for name,obj in items:
        if isinstance(obj, property): parts.append(_fmt_method(name, obj.fget, '@property\n    ').strip())
        elif callable(obj) and not _dynamic(obj): parts.append(_fmt_method(name, obj).strip())
        else:
            d = docstring(type(obj)).splitlines() if _dynamic(obj) else []
            comment = f'  # {d[0]}' if d else ''
            parts.append(f'- {name}: {type(obj).__name__}{comment}')
    parts.append('\nOverview only. Read `doc(obj.member)` for entries marked …; inspect properties on the class without evaluating them.')
    return PrettyString('\n'.join(parts))

# %% ../nbs/00_core.ipynb #c22af8b2
@allow
def docfind(o:str|object, q:str, n:int=2, _pre:str=''):
    "Search `doc()` recursively through `xdir(o)`, looking at submodules, classes, and functions, to depth `n`"
    pat = re.compile(q, re.IGNORECASE)
    res = []
    if isinstance(o, str): o = resolve(o)
    try: d = doc(o) or ''
    except: d = ''
    if pat.search(d): res.append(_pre + ' // ' + d.split('\n')[0])
    if n > 0:
        for k in xdir(o):
            try: child = getattr(o, k)
            except: continue
            nm = f'{_pre}.{k}' if _pre else k
            res += docfind(child, q, n-1, nm)
    return res

# %% ../nbs/00_core.ipynb #a486485f
def pyskills_dir():
    "Directory for user pyskills"
    return xdg_data_home() / 'pyskills'

def ensure_pyskills_dir():
    "Create xdg pyskills dir and .pth file if needed"
    sd = str(pyskills_dir())
    if sd in sys.path: return
    Path(sd).mkdir(parents=True, exist_ok=True)
    sps = site.getsitepackages()
    try: sps.append(site.getusersitepackages())
    except AttributeError: pass
    for sp in sps:
        pth = Path(sp) / 'pyskills.pth'
        if pth.exists() and sd in pth.read_text(): break
        try:
            Path(sp).mkdir(parents=True, exist_ok=True)
            pth.write_text(sd + '\n')
            break
        except (PermissionError, OSError): pass
    sys.path.append(sd)

# %% ../nbs/00_core.ipynb #2b3b357f
ensure_pyskills_dir()

# %% ../nbs/00_core.ipynb #553b1fbd
def clear_mod(prefix):
    "Clear modules starting with `prefix` from python caches"
    for k in list(sys.modules):
        if k.startswith(prefix): del sys.modules[k]
    importlib.invalidate_caches()

# %% ../nbs/00_core.ipynb #6ba14c44
def _pyskill_dist(name): return pyskills_dir() / f'{name.replace(".", "_")}-0.0.1.dist-info'

def enable_pyskill(name):
    "Enable pyskill `name` by creating its dist-info entry point"
    di = _pyskill_dist(name)
    di.mkdir(exist_ok=True)
    (di / 'METADATA').write_text(f'Name: {name.replace(".", "_")}\nVersion: 0.0.1\n')
    (di / 'entry_points.txt').write_text(f'[pyskills]\n{name} = {name}\n')
    clear_mod(name.split('.')[0])

def register_pyskill(name, docstr, code=''):
    "Register a pyskill module `name` in the xdg pyskills dir"
    sd = pyskills_dir()
    parts = name.split('.')
    mod_dir = sd / Path(*parts[:-1]) if len(parts) > 1 else sd
    mod_dir.mkdir(parents=True, exist_ok=True)
    for i in range(len(parts)-1): (sd / Path(*parts[:i+1]) / '__init__.py').touch()
    (mod_dir / f'{parts[-1]}.py').write_text(f'"""{docstr}"""\n{code}')
    enable_pyskill(name)

# %% ../nbs/00_core.ipynb #b80e18a8
def disable_pyskill(name):
    "Disable pyskill `name` by removing its dist-info entry point"
    di = _pyskill_dist(name)
    if di.exists(): shutil.rmtree(di)
    clear_mod(name.split('.')[0])

# %% ../nbs/00_core.ipynb #1e4f4c4c
def delete_pyskill(name):
    "Delete pyskill `name` module files and dist-info"
    disable_pyskill(name)
    sd = pyskills_dir()
    parts = name.split('.')
    mod_file = sd / Path(*parts[:-1]) / f'{parts[-1]}.py' if len(parts) > 1 else sd / f'{parts[-1]}.py'
    if mod_file.exists(): mod_file.unlink()

# %% ../nbs/00_core.ipynb #785498bf
from importlib.metadata import Distribution, DistributionFinder
from importlib.machinery import PathFinder

# %% ../nbs/00_core.ipynb #dd1a7b43
class _LocalSkillDistribution(Distribution):
    def __init__(self, finder): self.finder = finder
    def read_text(self, filename):
        if filename=='METADATA': return 'Name: pyskills-local\nVersion: 0\n'
        if filename=='entry_points.txt': return '[pyskills]\n' + '\n'.join(f'{n} = {n}' for n in self.finder.sources())
    def locate_file(self, path): return self.finder.folder/path

class _LocalSkills(DistributionFinder):
    _pyskills_local = True
    def __init__(self, folder):
        self.folder = folder
        self.roots = [str(p/'PYSKILLs') for p in (folder, *folder.parents)]

    def sources(self):
        res = {}
        for root in self.roots:
            for p in sorted(Path(root).glob('*')):
                name = p.stem if p.suffix=='.py' else p.name
                src = p if p.is_file() and p.suffix=='.py' else p/'__init__.py'
                if name.isidentifier() and not name.startswith('_') and src.is_file(): res.setdefault(name, src)
        return res

    def check_names(self):
        for name,src in self.sources().items():
            spec = importlib.util.find_spec(name)
            if spec is not None and (not spec.origin or Path(spec.origin).resolve()!=src.resolve()):
                raise ValueError(f'Local skill {name!r} conflicts with an existing import at {spec.origin!r}')

    def find_spec(self, fullname, path=None, target=None):
        if path is None and fullname in self.sources(): return PathFinder.find_spec(fullname, self.roots, target)

    def find_distributions(self, context=DistributionFinder.Context()):
        if context.name and re.sub(r'[-_.]+', '-', context.name).lower()!='pyskills-local': return
        importlib.invalidate_caches()
        self.check_names()
        yield _LocalSkillDistribution(self)


# %% ../nbs/00_core.ipynb #762f7eed
def enable_local_skills(
    folder:str|Path, # Opening directory whose ancestor PYSKILLs folders supply skills; expands ~ and resolves relative paths
)->DistributionFinder: # The installed finder; repeated activation for the same directory returns it
    """Enable folder-local skill imports and entry points for this interpreter.

    Call once at host startup. Later cwd changes do not alter the scope. A different folder after activation raises ValueError; use a new kernel. Local skill names conflicting with other importable modules also raise ValueError. No skill code is executed during activation or discovery, and no metadata files are written.
    """
    folder = Path(folder).expanduser().resolve()
    if not folder.is_dir(): raise NotADirectoryError(folder)
    for finder in sys.meta_path:
        if not getattr(finder, '_pyskills_local', False): continue
        if finder.folder!=folder: raise ValueError(f'Local skills already enabled for {finder.folder}')
        return finder
    finder = _LocalSkills(folder)
    finder.check_names()
    sys.meta_path.append(finder)
    importlib.invalidate_caches()
    return finder
