"""Functions for creating, viewing, and modifying files. Each editing operation returns unified diffs showing what changed.

## File viewing, creating, and editing

File tools take a filesystem path as the first argument, e.g:

file_view('~/a/b.py', 3)
file_create('~/a/b/c.py', 'content here')
file_str_replace('myfile.py', 'old_name', 'new_name')
file_del_lines('myfile.py', 2, 4)

## Line filtering

`file_str_replace`, `file_strs_replace`, and `file_del_lines` support `re_filter` and `invert_filter` for targeting only lines matching (or not matching) a regex, like ex's `g//` and `g!//`. Combined with `start_line`/`end_line` to restrict to a region, e.g:

file_del_lines('myfile.py', 1, -1, re_filter=r'^\s*#')       # delete all comment lines

Docs: https://AnswerDotAI.github.io/pyskillsedit.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_edit.ipynb.

# %% auto #0
__all__ = ['file_insert_line', 'file_str_replace', 'file_strs_replace', 'file_replace_lines', 'file_del_lines', 'file_view',
           'file_create', 'file_edit', 'insert_line', 'str_replace', 'strs_replace', 'replace_lines', 'del_lines']

# %% ../nbs/01_edit.ipynb #fed1068a
import difflib,re
from pathlib import Path
from tempfile import TemporaryDirectory
from fnmatch import translate

from fastcore.utils import globtastic
from fastcore.meta import splice_sig, delegates

# %% ../nbs/01_edit.ipynb #8478e86e
def file_view(
    path:str, # Path to view (expands `~` if needed)
    startline:int=1, # Starting line to view
    endline:int=None # End line (defaults to last line if None)
):
    "Read file contents, optionally limited to 1-based line range"
    path = Path(path).expanduser()
    lines = path.read_text().splitlines()
    if not lines: return ''
    if endline is None: endline = len(lines)
    if endline < 0: endline = len(lines)+endline+1
    if not (1 <= startline <= len(lines)): return f'error: Invalid startline {startline}. Valid range: 1-{len(lines)}'
    if endline > len(lines): endline = len(lines)
    return '\n'.join(f'{i}: {l}' for i,l in enumerate(lines[startline-1:endline], startline))

# %% ../nbs/01_edit.ipynb #84615568
def file_create(
    path:str, # Path to create (expands `~` if needed)
    contents:str # Contents of file to create
):
    "Create a new file with contents. Error if file exists."
    path = Path(path).expanduser()
    if path.exists(): return f'error: File exists: {path}'
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(contents)
    return 'done'

# %% ../nbs/01_edit.ipynb #7537dcf1
_file_edit_doc = """
This is a *file* editing function.

File editing standard parameter is `path`: Path to the file to modify

returns: diff of changes, or "none: No changes.", or "error: ..."
"""

# %% ../nbs/01_edit.ipynb #430316a1
def file_edit(f, name=None):
    def wrapper(path:str, *args, **kw):
        path = Path(path).expanduser()
        text = path.read_text()
        try: new_text = f(text, *args, **kw)
        except ValueError as e: return f'error: {e}'
        Path(path).write_text(new_text)
        diff = '\n'.join(list(difflib.unified_diff(text.splitlines(), new_text.splitlines(), n=1, lineterm=''))[2:])
        return diff or 'none: No changes.'
    res = splice_sig(wrapper, f, 'text')
    if name: res.__name__ = res.__qualname__ = name
    res.__doc__ = (f.__doc__ or '') + _file_edit_doc
    return res

# %% ../nbs/01_edit.ipynb #b694c73a
def insert_line(
    text:str,
    insert_line:int, # The 1-based line number after which to insert the text (0: before 1st line, n>=1: after nth line)
    new_str:str, # The text to insert
):
    "Insert new_str at specified line number"
    lines = text.splitlines()
    if not (0 <= insert_line <= len(lines)): raise ValueError(f'Invalid line {insert_line}. Valid range: 0-{len(lines)}')
    lines.insert(insert_line, new_str)
    return '\n'.join(lines)

file_insert_line = file_edit(insert_line, 'file_insert_line')

# %% ../nbs/01_edit.ipynb #52428b51
def str_replace(
    text:str,
    old_str:str, # Text to find and replace
    new_str:str, # Text to replace with
    start_line:int=None, # Optional 1-based start line to limit search
    end_line:int=None, # Optional 1-based end line to limit search
    n_matches:int=None, # Max replacements (None=all)
    re_filter:str=None, # If provided, only process lines matching this regex (like g// in ex)
    invert_filter:bool=False, # Invert the filter (like g!// in ex)
):
    "Replace occurrence(s) of old_str with new_str"
    def _repl(s, label=''):
        if s.count(old_str) == 0: raise ValueError(f"Text not found{label}: {repr(old_str)}")
        return s.replace(old_str, new_str) if n_matches is None else s.replace(old_str, new_str, n_matches)
    if re_filter or start_line or end_line:
        lines = text.splitlines(True)
        s,e = (start_line or 1)-1, end_line or len(lines)
        if not re_filter: return ''.join(lines[:s]) + _repl(''.join(lines[s:e]), f' in lines {s+1}-{e}') + ''.join(lines[e:])
        pat = re.compile(re_filter)
        matched = [i for i in range(s,e) if bool(pat.search(lines[i])) != invert_filter]
        if not matched: return text
        for i in matched: lines[i] = _repl(lines[i], f' on line {i+1}')
        return ''.join(lines)
    return _repl(text)

file_str_replace = file_edit(str_replace, 'file_str_replace')

# %% ../nbs/01_edit.ipynb #487a9365
def strs_replace(
    text:str,
    old_strs:list[str], # List of strings to find and replace
    new_strs:list[str], # List of replacement strings (must match length of old_strs)
    start_line:int=None, # Optional 1-based start line to limit search
    end_line:int=None, # Optional 1-based end line to limit search
    n_matches:int=None, # Max replacements per string (None=all)
    re_filter:str=None, # If provided, only process lines matching this regex (like g// in ex)
    invert_filter:bool=False, # Invert the filter (like g!// in ex)
):
    "Replace multiple strings simultaneously"
    if not isinstance(old_strs, list): raise ValueError(f"`old_strs` should be a list[str] but got {type(old_strs)}")
    if not isinstance(new_strs, list): raise ValueError(f"`new_strs` should be a list[str] but got {type(new_strs)}")
    if len(old_strs) != len(new_strs): raise ValueError(f"Length mismatch: {len(old_strs)} old_strs vs {len(new_strs)} new_strs")
    for idx,(old_str,new_str) in enumerate(zip(old_strs, new_strs)):
        text = str_replace(text, old_str, new_str, start_line=start_line, end_line=end_line,
                            n_matches=n_matches, re_filter=re_filter, invert_filter=invert_filter)
    return text

file_strs_replace = file_edit(strs_replace, 'file_strs_replace')

# %% ../nbs/01_edit.ipynb #7558e897
def _norm_lines(n:int, start:int, end:int=None):
    "Normalize and validate line range. Returns (start, end) or raises ValueError."
    if end is None: end = start
    if end < 0: end = n + end + 1
    if not (1 <= start <= n): raise ValueError(f'Invalid start line {start}. Valid range: 1-{n}')
    if not (start <= end <= n): raise ValueError(f'Invalid end line {end}. Valid range: {start}-{n}')
    return start, end

# %% ../nbs/01_edit.ipynb #03685bf9
def replace_lines(
    text:str,
    start_line:int, # Starting line number to replace (1-based indexing)
    end_line:int=None, # Ending line number to replace (1-based, inclusive, negative counts from end, None for single line)
    new_content:str='', # New content to replace the specified lines
):
    "Replace line range with new content"
    lines = text.splitlines(keepends=True)
    s,e = _norm_lines(len(lines), start_line, end_line)
    if lines and new_content and not new_content.endswith('\n'): new_content += '\n'
    lines[s-1:e] = [new_content] if new_content else []
    return ''.join(lines)

file_replace_lines = file_edit(replace_lines, 'file_replace_lines')

# %% ../nbs/01_edit.ipynb #cc1b61a5
def del_lines(
    text:str,
    start_line:int, # Starting line number to delete (1-based indexing)
    end_line:int=None, # Ending line number to delete (1-based, inclusive, negative counts from end, None for single line)
    re_filter:str=None, # If provided, only delete lines matching this regex (like g// in ex)
    invert_filter:bool=False, # Invert the filter (like g!// in ex)
):
    "Delete line range"
    lines = text.splitlines(keepends=True)
    s,e = _norm_lines(len(lines), start_line, end_line)
    if re_filter:
        pat = re.compile(re_filter)
        matched = {i for i in range(s-1,e) if bool(pat.search(lines[i])) != invert_filter}
        if not matched: return text
        lines = [l for i,l in enumerate(lines) if i not in matched]
    else: del lines[s-1:e]
    return ''.join(lines)

file_del_lines = file_edit(del_lines, 'file_del_lines')
