"""Functions for searching, creating, and reading files.

Docs: https://AnswerDotAI.github.io/pyskillsfiles.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_files.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/01_files.ipynb #fed1068a
import difflib,re
from os.path import expanduser
from pathlib import Path
from tempfile import TemporaryDirectory
from fnmatch import translate

from fastcore.utils import globtastic
from fastcore.meta import splice_sig, delegates
