"""Functions for view/modifying ipynb file notebook cells. Each operation returns unified diffs showing what changed.

## Ipynb file cell editing

Cell tools take an ipynb path and a cell id, e.g:

cell_replace_lines('nb.ipynb', cell_id, 2, 3, 'replaced')
cell_insert_line('nb.ipynb', cell_id, 0, 'first line')

Use `view_nb` to view the whole notebook. Use `view_cell` to see a cell's source with line numbers before editing. Use `add_cell` to insert a new cell before/after an existing cell id, and `del_cells` to delete cells.

## Line filtering

`cell_str_replace`, `cell_strs_replace`, and `cell_del_lines` support `re_filter` and `invert_filter` for targeting only lines matching (or not matching) a regex, like ex's `g//` and `g!//`. Combine with `start_line`/`end_line` to restrict to a region.

Docs: https://AnswerDotAI.github.io/pyskills/ipynb.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_ipynb.ipynb.

# %% auto #0
__all__ = ['cell_insert_line', 'cell_str_replace', 'cell_strs_replace', 'cell_replace_lines', 'cell_del_lines', 'add_cell',
           'del_cells', 'view_cell', 'view_nb']

# %% ../nbs/02_ipynb.ipynb #fed1068a
import difflib,re
from pathlib import Path
from tempfile import TemporaryDirectory

from fastcore.meta import splice_sig
from .edit import *

# %% ../nbs/02_ipynb.ipynb #005ca01f
_cell_edit_doc = f"""
Be sure you've called `view_cell(…)` to ensure you know the line nums.

Cell editing standard parameters:

id: Cell id to edit, or list of ids, or 'all' for all messages in file
fname: ipynb to get info for
update_output: If True, replace in output instead of content

returns:
- For single id: diff of changes, or "none: No changes.", or "error: ..."
- For id list (or 'all'): list of tuples of (id,diff) for changed messages"""

# %% ../nbs/02_ipynb.ipynb #393c0016
def _cell_edit(f, name=None):
    def wrapper(fname:str, id:str|list[str], *args, update_output:bool=False, **kw):
        nb = Notebook.open(fname)
        def _one(cid):
            cell = nb[cid]
            text = str(cell.outputs) if update_output else cell.source
            if not text: return f"error: Cell has no {'output' if update_output else 'source'}"
            try: new_text = f(text, *args, **kw)
            except ValueError as e: return f'error: {e}'
            if update_output: cell.outputs = ast.literal_eval(new_text)
            else: nb[cid] = new_text
            diff = '\n'.join(list(difflib.unified_diff(text.splitlines(), new_text.splitlines(), n=1, lineterm=''))[2:])
            return diff or 'none: No changes.'
        if isinstance(id, list) or id == 'all':
            if id == 'all': id = [c.id for c in nb.cells]
            res = [(cid, r) for cid in id if not (r := _one(cid)).startswith(('error:', 'none:'))]
        else: res = _one(id)
        nb.save()
        return res
    res = splice_sig(wrapper, f, 'text')
    if name: res.__name__ = res.__qualname__ = name
    res.__doc__ = (f.__doc__ or '') + _cell_edit_doc
    return res

# %% ../nbs/02_ipynb.ipynb #d0b5622f
from fastcore.nbio import *

# %% ../nbs/02_ipynb.ipynb #b7635c87
cell_insert_line = _cell_edit(insert_line, 'cell_insert_line')
cell_str_replace = _cell_edit(str_replace, 'cell_str_replace')
cell_strs_replace = _cell_edit(strs_replace, 'cell_strs_replace')
cell_replace_lines = _cell_edit(replace_lines, 'cell_replace_lines')
cell_del_lines = _cell_edit(del_lines, 'cell_del_lines')

# %% ../nbs/02_ipynb.ipynb #3bdf5927
def add_cell(fname:str, # ipynb to edit
             source:str, # source for the new cell
             cell_type:str='code', # 'code', 'markdown', or 'raw'
             before:str=None, # id of cell to insert before
             after:str=None): # id of cell to insert after
    "Add a new cell before/after an existing cell (pass exactly one), returning the new cell's id"
    if (before is None)==(after is None): raise ValueError('Pass exactly one of `before` or `after`')
    nb = Notebook.open(fname)
    idx = nb.cells.index(nb[before or after]) + (after is not None)
    cell = mk_cell(source, cell_type)
    nb.cells.insert(idx, cell)
    nb.save()
    return cell.id

# %% ../nbs/02_ipynb.ipynb #9e1fb838
def del_cells(fname:str, # ipynb to edit
              *ids:str): # ids of cells to delete
    "Delete cells by id"
    nb = Notebook.open(fname)
    for i in ids: del nb[i]
    nb.save()

# %% ../nbs/02_ipynb.ipynb #e8a9b077
def view_cell(fname:str, id:str, nums:bool=True):
    "Show cell source with optional line numbers"
    return Notebook.open(fname).view(id, nums=nums)

# %% ../nbs/02_ipynb.ipynb #89723255
def view_nb(fname:str, incl_out:bool=False):
    "Show notebook source as concise xml, optionally including output if `incl_out`"
    nb = Notebook.open(fname)
    return repr(nb) if incl_out else nb.concise
